INSERT INTO user  (ID, COLOR , NAME , PARENTID ) VALUES (2,'green','Wizard',0);
INSERT INTO user  (ID, COLOR , NAME , PARENTID ) VALUES (3,'white','Priest',0);
INSERT INTO user  (ID, COLOR , NAME , PARENTID ) VALUES (4,'yellow','Rogue',0);
INSERT INTO user  (ID, COLOR , NAME , PARENTID ) VALUES (5,'blue','Fighter',1);
INSERT INTO user  (ID, COLOR , NAME , PARENTID ) VALUES (6,'lighblue','Paladin',1);
INSERT INTO user  (ID, COLOR , NAME , PARENTID ) VALUES (7,'lighgreen','Ranger',1);
INSERT INTO user  (ID, COLOR , NAME , PARENTID ) VALUES (8,'grey','Mage',2);
INSERT INTO user  (ID, COLOR , NAME , PARENTID ) VALUES (9,'lightgrey','Specialist wizard',2);
INSERT INTO user  (ID, COLOR , NAME , PARENTID ) VALUES (10,'red','Cleric',3);
INSERT INTO user  (ID, COLOR , NAME , PARENTID ) VALUES (11,'green','Druid',3);
INSERT INTO user  (ID, COLOR , NAME , PARENTID ) VALUES (12,'white','Priest of specific mythos',3);
INSERT INTO user  (ID, COLOR , NAME , PARENTID ) VALUES (13,'yellow','Thief',4);
INSERT INTO user  (ID, COLOR , NAME , PARENTID ) VALUES (14,'blue','Bard',4);
INSERT INTO user  (ID, COLOR , NAME , PARENTID ) VALUES (15,'lighblue','Assassin',13);
INSERT INTO user  (ID, COLOR , NAME , PARENTID ) VALUES (1,'red','Warrior',0);